/**
 * IQOption Event.
 */
export enum IQOptionEvent {
    SEND_ORDER_BINARY = "SEND_ORDER_BINARY",
    SEND_ORDER_BINARY_DISPATCHER = "SEND_ORDER_BINARY_DISPATCHER",
    CONNECT_ASYNC = "CONNECT_ASYNC",
    PROFILE_ASYNC = "PROFILE_ASYNC"
}
