export enum StrategyEvent {
    SHOW_INFORMATION = "SHOW_INFORMATION",
    NEW_TARGET = "NEW_TARGET",
    CHECK_NEW_TARGET = "CHECK_NEW_TARGET",
    LOAD_INITIALIZATION_DATA = "LOAD_INITIALIZATION_DATA"
}
